# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Deutsche Übersetzung in Arbeit - lesen Sie Englisch hier"
  url = "https://www.christophcemper.com/"
  weight = 10

[[main]]
  name = "Publikationen"
  url = "https://www.christophcemper.com/de/publication"
  weight = 30

[[main]]
  name = "Photos"
  url = "https://www.christophcemper.com/publication/photos/"
  weight = 60

[[main]]
  name = "Contact"
  url = "/#contact"
  weight = 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "/media/resume.pdf"
#    weight = 70
