[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "/entrepreneurship/*"
  to =   "/blog/learning/entrepreneurship/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
#  edge_handler = "filterRequests"

  from = "/success/*"
  to =   "/blog/learning/success/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
#  edge_handler = "filterRequests"

  from = "/personal-development/*"
  to =   "/blog/learning/personal-development/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

  from = "/digital-marketing/*"
  to =   "/blog/learning/digital-marketing/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

  from = "/digital-leadership/*"
  to =   "/blog/learning/leadership/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"
