[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "/entrepreneurship/*"
  to =   "/blog/learning/entrepreneurship/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
#  edge_handler = "filterRequests"

[[redirects]]
  from = "/success/*"
  to =   "/blog/learning/success/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
#  edge_handler = "filterRequests"

[[redirects]]
  from = "/personal-development/*"
  to =   "/blog/learning/personal-development/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

[[redirects]]
  from = "/digital-marketing/*"
  to =   "/blog/learning/digital-marketing/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

[[redirects]]
  from = "/digitalmarketing/*"
  to =   "/blog/learning/digital-marketing/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"


[[redirects]]
  from = "/digital-leadership/*"
  to =   "/blog/learning/leadership/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"


[[redirects]]
  from =   "/blog/learning/digital-leadership/:splat"
  to =   "/blog/learning/leadership/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"


[[redirects]]
  from = "/software-engineering/*"
  to =   "/blog/learning/software-engineering/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

[[redirects]]
  from = "/branding/*"
  to =   "/blog/learning/branding/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

[[redirects]]
  from = "/pricing/*"
  to =   "/blog/learning/pricing/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

[[redirects]]
  from = "/selling/*"
  to =   "/blog/learning/sales/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

[[redirects]]
  from = "/blog/learning/:cat/:post/"
  to =   "/blog/learning/:post/"
  status = 301
  force = false #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"


## fix those paginations
[[redirects]]
  from = "/blog/learning/*/page/:page_number/"
  to =   "/tag/:splat/page/:page_number"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"

## fix those paginations


[[redirects]]
  from = "/blog/learning/success/bring-your-business-life-to-a-new-level-at-this-sold-out-event/"
  to =   "/blog/bring-your-business-life-to-a-new-level-at-this-sold-out-event/"
  status = 301
  force = true #COMMENT: ensure that we always redirect
  #  edge_handler = "filterRequests"
